# starshipã®è¨­å®š
# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

## åŸºæœ¬
add_newline = true

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "â€¦/"
style = "#AA96DA bold"

[container]
disabled = true

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"

[gcloud]
disabled = true

[username]
style_user = "#A8D8EA bold"
format = "[ïŠ¾ $user]($style) in "
disabled = false
show_always = true

[git_branch]
style = "#FCBAD3"
[git_status]
style = "#FCBAD3"
conflicted = 'âš”ï¸'
ahead = 'ğŸğŸ’¨'
behind = 'ğŸ˜°'
diverged = 'ğŸ˜µ'
up_to_date = 'âœ…'
untracked = 'ğŸ¾'
stashed = 'ğŸ“¦'
modified = 'ğŸ”¨'
staged = '[++\($count\)](green)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'
