# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = "$all$custom_git_username"

[character]
success_symbol = "[❯](purple bold)"
error_symbol = "[❯](red bold)"
vimcmd_symbol = "[❮](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"
style = "#7071E8 bold"

[container]
disabled = true

[docker_context]
format = "via [󰡨 $context](blue bold) "

[gcloud]
disabled = false
symbol = '️󱇶 '
format = "on $symbol[$project]($style) "

[aws]
disabled = true

[cmd_duration]
disabled = true

[username]
style_user = "#A8D8EA bold"
format = "[ $user]($style) in "
disabled = true
show_always = true

[git_branch]
style = "#F875AA"
symbol = " "

[git_status]
style = "#F875AA"
format = '([$all_status$ahead_behind]($style))'
conflicted = '[= ](pink)'
ahead = '[⇡$ahead_count](pink)'
behind = '[⇣$behind_count](pink)'
modified = '[ ](pink)'
deleted = '[󱎘 ](pink)'
untracked = '[ ](pink)'
staged = '[󰸞 ](pink)'
stashed = '[󰉀 ](pink)'

[package]
style = "#E1AEFF"
symbol = " "

[nodejs]
style = "#FFBDF7"
symbol = "󰋙 "

[python]
style = "#FFBDF7"
symbol = " "

[bun]
style = "#FFBDF7"
symbol = "󱁣 "

[custom.git_username]
description = "<custom config for git username>"
command = "git config user.name"
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"
format = "[󰀄$output]($style)"
style = "#F875AA"
